openapi: 3.0.0
info:
  version: 1.0.0
  title: DPCOde Academy API
  description: |
    DPCOde Academy API <br>
    Basically for optional column, it returns a blank instead of null if there is no value.

servers:
  - url: https://localhost:8000

security:
  - BasicAuth: []

paths:
  /user:
    get:
      tags:
        - user
      description: Get all students data.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - user
      summary: Create a new user with token id
      requestBody:
        description: | 
          Create a new user with token id. <br>
          id is required, but other values are optional
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "string"
                  description: |
                    <span style="color: red; ">*required</span> token id
                first_name:
                  type: "string"
                  description: |
                    \<Optional> User's first name
                last_name:
                  type: "string"
                  description: |
                    \<Optional> User's last name
                image_path:
                  type: string
                  description: |
                    \<Optional> The path of a user's profile image
                birth:
                  type: string
                  format: yyyy-MM-dd HH:mm:ss.sss
                  description:  |
                    \<Optional> User's birth day
                email:
                  type: string
                  format: email
                  description:  |
                    \<Optional> User's email
                phone:
                  type: string
                  description:  |
                    \<Optional> User's phone number
              example:
                - id: 442c16a8a353
                  first_name: Brooklyn
                  last_name: Beckham
                  image_path: "https://sampledata.png"
                  birth: "1994-01-24 00:00:00"
                  email: student1@gmail.com
                  phone: 123-456-7890

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
                example:
                  - id: 442c16a8a353
                    first_name: Brooklyn
                    last_name: Beckham
                    image_path: "https://sampledata.png"
                    birth: "1994-01-24 00:00:00.000"
                    email: student1@gmail.com
                    phone: 123-456-7890
                    parent_first_name": ""
                    parent_last_name": ""
                    parent_email: ""
                    parent_phone: ""
                    type: student
                    updated_date: "2021-05-22 10:00:40.838"
                    created_date: "2021-05-20 22:00:40.464"

        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/{token}:
    get:
      tags:
        - user
      description: Get specific student data by token.
      parameters:
        - $ref: "#/components/parameters/PageLimit"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 1
                name: David Beckham
                birth: 2000/12/12
                email: student1@gmail.com
                phone: 1231231233
                address: Vancouver
        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /students/{token}/courses:
    get:
      tags:
        - user
      description: Get courses of specific student has.
      parameters:
        - $ref: "#/components/parameters/PageLimit"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"
                example:
                  - id: 1
                    name: Python
                    duration: duration
                    schedules:
                      - 2021/05/10
                      - 2021/05/11
                      - 2021/05/12
                    description: Python for beginners.
                    image_path: /img/courses/card.jpg
                    features:
                      - 1
                      - 2
                      - 3
                    level: Beginner
                    prerequisites:
                      - 1
                      - 2
                    price: 2000
                    status: normal
                  - id: 2
                    name: Algorithm
                    duration: duration
                    schedules:
                      - 2021/05/13
                      - 2021/05/14
                      - 2021/05/15
                    description: Algorithm for intermediates.
                    image_path: /img/courses/card.jpg
                    features:
                      - 1
                    level: Intermediate
                    prerequisites:
                      - 1
                      - 3
                      - 5
                    price: 3500
                    status: hard
        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /courses:
    get:
      tags:
        - courses
      description: Get all courses data.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"
                example:
                  - id: 1
                    name: Python
                    duration: duration
                    schedules:
                      - 2021/05/10
                      - 2021/05/11
                      - 2021/05/12
                    description: Python for beginners.
                    image_path: /img/courses/card.jpg
                    features:
                      - 1
                      - 2
                      - 3
                    level: Beginner
                    prerequisites:
                      - 1
                      - 2
                    price: 2000
                    status: normal
                  - id: 2
                    name: Algorithm
                    duration: duration
                    schedules:
                      - 2021/05/13
                      - 2021/05/14
                      - 2021/05/15
                    description: Algorithm for intermediates.
                    image_path: /img/courses/card.jpg
                    features:
                      - 1
                    level: Intermediate
                    prerequisites:
                      - 1
                      - 3
                      - 5
                    price: 3500
                    status: hard
    post:
      tags:
        - courses
      description: Create a new Course.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Course"
            example:
              name: Java
              schedules:
                - 2021/05/15
                - 2021/05/16
              description: Java fro beginners.
              image_path: /img/courses/card.jpg
              price: 2799
              status: hard
      responses:
        200:
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"

  /courses/{id}:
    get:
      tags:
        - courses
      description: Get specific courses data by id.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - courses
      description: Update specific course data by id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Course"
            example:
              id: 3
              name: Swift
              schedules:
                - 2021/05/17
              description: Swift fro beginners.
              image_path: /img/courses/card.jpg
              price: 4000
              status: normal
      responses:
        200:
          description: updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
              example:
                id: 3
                name: Swift
                schedules:
                  - 2021/05/17
                description: Swift fro beginners.
                image_path: /img/courses/card.jpg
                price: 4000
                status: normal
        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - courses
      description: Delete specific course data by id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Course"
            example:
              id: 2
      responses:
        200:
          description: deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
              example:
                id: 2
        default:
          description: error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /courses/{course_id}/user:
    post:
      tags:
        - courses
      description: Add a user to a course
      parameters:
      - name: course_id
        in: path
        description: Course id
        required: true
        schema:
          type: string 
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: string
                  description: |
                    <span style="color: red; ">*required</span> User's social account unique token id
              example:
                - user_id: eyJz9sdfsdfsdfsd

      responses:
        200:
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"


components:
  parameters:
    PageLimit:
      name: limit
      in: query
      description: Limits the number
      schema:
        type: integer

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 442c16a8a353
          description: |
            User's social account unique token id
        first_name:
          type: string
          example: Brooklyn
          description: |
            User's first name
        last_name:
          type: string
          example: Beckham
          description: |
            User's last name
        image_path:
          type: string
          example: "https://sampledata.png"
          description: |
            The path of a user's profile image
        birth:
          type: string
          format: yyyy-MM-dd HH:mm:ss.sss
          example: "1994-01-24 00:00:00.000"
          description: |
            User's birth day
        email:
          type: string
          format: email
          example: student1@gmail.com
          description: |
            User's email
        phone:
          type: string
          example: 123-456-7890
          description: |
            User's phone number
        parent_first_name:
          type: string
          example: David
          description: |
            Optional<br>
            User's parents first name
        parent_last_name:
          type: string
          example: Beckham
          description: |
            Optional<br>
            User's parents last name
        parent_email:
          type: string
          format: email
          example: parent1@gmail.com
          description: |
            Optional<br>
            User's parents email
        parent_phone:
          type: string
          example: 456-789-0123
          description: |
            Optional<br>
            User's parents phone number
        type:
          type: string
          example: student
          description: |
            User's type<br>
            Acceptable values are:
            - student
            - admin
        updated_date:
          type: string
          format: yyyy-MM-dd HH:mm:ss.sss
          example: "2021-05-22 10:00:40.838"
          description: |
            updated date
        created_date:
          type: string
          format: yyyy-MM-dd HH:mm:ss.sss
          example: "2021-05-20 22:00:40.464"
          description: |
            created date

    Course:
      type: object
      properties:
        id:
          type: string
          description: |
            Unique course ID
        name:
          type: string
          description: |
            Course name
        category:
          type: string
          description: |
            Course category
        status:
          type: string
          description: |
            Course status<br>
            Acceptable values are:
            - archived - finished course
            - active - now opening course
            - inactive - future course
        start_date:
          type: string
          format: dd/mm/yyyy
          description: |
            course start date
        end_date:
          type: string
          format: dd/mm/yyyy
          description: |
            course end date
        class_schedules:
          type: array
          items:
            properties:
              start_time:
                type: string
                format: dd/mm/yyyy
              end_time:
                type: string
                format: dd/mm/yyyy
          description: |
            A list of class schedules including a start date and an end date of a class.
        description:
          type: string
          description: |
            A description of a course 
        image_path:
          type: string
          description: |
            A image path of a course
        features:
          type: array
          items:
            type: string
          description: |
            A list of features of a course
        level:
          type: string
          description: |
            The level of a course<br>
            Acceptable values are:
            - Beginner
            - Intermediate
            - Advanced
        prerequisites:
          type: array
          items:
            type: string
          description: |
             Courses, conditions, presimes, and status recommended to have before apply this course
        length:
          type: object
          properties:
            month:
              type: number
            weeks:
              type: number
            hours:
              type: number
          description: |
            An object including course month, weeks, and hours
        price:
          type: object
          properties:
            $:
              type: number
            hours:
              type: number
            periodicity:
              type: string
          description: |
            An object including course price, hours, and periodicity
        available_schedules:
          type: array
          items:
            type: string
            format: dd/mm/yyyy
          description:
            A list of available course schedules
        updated_date:
          type: string
          format: yyyy-MM-dd HH:mm:ss.sss
          description: |
            updated date
        created_date:
          type: string
          format: yyyy-MM-dd HH:mm:ss.sss
          description: |
            created date

  # Tak
    Status:
      type: object
      properties:
        user_id:
          type: string
          example: eyJz9sdfsdfsdfsd
          description: |
            Unique user ID which belongs to the course_id.
        course_id:
          type: string
          example: DPCS100#1
          description: |
            Unique course ID which belongs to the user_id. 
        status:
          type: string
          example: registered
          description: |
            A user's status for the course (course_id).<br>
            There are four status: <br>
            - wait list
              - A user who applied but not in the process because the course is not ready (the course is "inactive"). 
            - applied
              - A user who already applied but hasn't registered (got interview or paid tuition fee) yet.
            - registered
              - A user who already registered (got interview and paid tuition free) to the course. 
            - resign
              - A user who quit the class for some reason.

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              example: Unexpected parameters received
            code:
              type: integer
              minimum: 100
              maximum: 600
              example: 190
